<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<!-- <div class="toolbar-sorter sorter"> -->
    <label class="font12 mr-2 mb-0" for="sorter"><?= $block->escapeHtml(__('Sort By')) ?></label>
    <div class="custom_select">                                                                                           
        <select id="sorter" data-role="sorter" class="font12 roboto_bold pl-2 pr-5 py-1 mb-1" style="height: 30px;">
            <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
                <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                    <?php if ($block->isOrderCurrent($_key)) :?>
                        selected="selected"
                    <?php endif; ?>
                    >
                    <?= $block->escapeHtml(__($_order)) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>
    <?php if ($block->getCurrentDirection() == 'desc') :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc">
            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php else :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="#"
           class="action sorter-action sort-asc"
           data-role="direction-switcher"
           data-value="desc">
            <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
    <?php endif; ?>
<!-- </div> -->
