<?php
/**
 * Category sidebar
 *
 * @var $block Synapse\Sidebar\Block\Sidebar
 */
$categories = $block->getCategories(); 
$brands     = $block->getBrands();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$currentCategory = $objectManager->get('Magento\Framework\Registry')->registry('current_category');

//echo "Current Cat: " . $currentCategory->getName() . "<br> Id : ". $currentCategory->getId() . "<br>";

?>
<div class="block-content filter-content">
	<div class="filter-options" id="narrow-by-list rdlist" data-role="content" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": "0", "multipleCollapsible": true}}'>
		<div data-role="collapsible" class="filter-options-item">
			<div data-role="title" class="filter-options-title font14 heading_text pb-1"><?php echo __('Categories'); ?></div>
			<div data-role="content" class="filter-options-content">
				<ul class="o-list">

					<?php
					// Loop through categories
					foreach ( $categories as $category ) :
					
					//$collapsibleRange = implode(' ', range(0, $categories->getItemsCount()));
						//echo"<pre>"; print_r($category->debug()); echo "<br>Name: " . $category->getName(); 
						
						//echo $block->getCategoryUrl($category);
						
						//die("RD");
						if( $category->getName() != "Themes" ) :
						?>
						<li class="level0<?php echo($block->isActive($category) ? ' active' : ''); ?>">
							<a href="<?php echo $block->getCategoryUrl($category); ?>" title="<?php echo $category->getName(); ?>" class="<?php echo($block->isActive($category) ? ' active' : ''); ?>">
								<?php echo $category->getName(); ?>
							</a>
							<?php //if ( $category->hasChildren() ) : ?>
								<!-- span class="expand"><?php //echo $block->isActive($category) ? '<i class="fa fa-minus"></i>' : '<i class="fa fa-plus"></i>'; ?></span -->
							<?php //endif; ?>

							<?php echo $block->getChildCategoryView($category); ?>
						</li>
					<?php endif; endforeach; ?>
				</ul>
			</div>
		</div>
	</div>
</div>


<script type="text/javascript">
	/* Simply invoke iffe of sidebarmodule */
	require(['jquery','sidebarmodule'], function ($) {});
</script>