<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt()
?>

<span data-action="toggle-nav" class="action nav-toggle"><span><?= $block->escapeHtml(__('Toggle Nav')) ?></span></span>
<div class="logo_padding pt-2 pb-3">
	<a
		class="logo_rdlogo"
		href="<?= $block->escapeUrl($block->getUrl('')) ?>"
		title="<?= $block->escapeHtmlAttr($storeName) ?>"
		aria-label="store logo">
		<img src="<?= $block->escapeUrl($block->getLogoSrc()) ?>"
			 title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>" class="img-fluid"
			 alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
				<?= $block->getLogoWidth() ? 'width="' . $block->escapeHtmlAttr($block->getLogoWidth()) . '"' : '' ?>
				<?= $block->getLogoHeight() ? 'height="' . $block->escapeHtmlAttr($block->getLogoHeight()) . '"' : '' ?>
		/>
	</a>
</div>


