
<div class="d-flex">
	<a class="sprd-header__link-mp js-header-main-mp is-active top_menus active mr-xl-5 mr-3" href="#">
		<div class="font20 heading_text title">Shop</div>
		<div class="font12 description">Explore Products</div>
	</a>
	<a class="top_menus sprd-header__link-mp js-header-main-mp is-active" href="#">
		<div class="font20 heading_text title">Design</div>
		<div class="font12 description">Create your own</div>
	</a>
</div>

